### ISSUE TITLE
深度学习实现方案

### ISSUE THREAD

**Issue by daixiongming** [ssochi/Fire_detection#1]
您好！我下载您的包跑了一下，那个深度学习的框架没有实现，是吗？您正在做，对吗？期待您的回复。

**Comment by ssochi** [comment]
https://github.com/ssochi/Fire_detection/blob/master/DeepLearnToolbox/CNN/New%20Folder/Test_example_CNN.m
这个是训练的
https://github.com/ssochi/Fire_detection/blob/master/DeepLearnToolbox/CNN/New%20Folder/test.m
这个是测试
效果一般 速度慢 模型都没改 很水
